Models/BikeBuilder.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace _1FinalCapstone.Models
{
    public partial class BikeBuilder
    {
        public int BuilderId { get; set; }

        [Required(ErrorMessage = "Step Title is required")]
        public string StepTitle { get; set; }

        [Required(ErrorMessage = "Builder Title is required")]
        public string BuilderTitle1 { get; set; }

        [Required(ErrorMessage = "Builder Description is required")]
        public string BuilderDescription1 { get; set; }

        [Required(ErrorMessage = "Bprice is required")]
        [NonNegativeAndNonZero(ErrorMessage = "Bprice must be greater than 0.")]
        public int Bprice1 { get; set; }

        public byte[] BImage1 { get; set; }
        public string BuilderTitle2 { get; set; }
        public string BuilderDescription2 { get; set; }
        public Nullable<int> Bprice2 { get; set; }
        public byte[] BImage2 { get; set; }
        public string BuilderTitle3 { get; set; }
        public string BuilderDescription3 { get; set; }
        public Nullable<int> Bprice3 { get; set; }
        public byte[] BImage3 { get; set; }
        public string ArchiveStatus { get; set; }
    }
}

public class NonNegativeAndNonZeroAttributes : ValidationAttribute
{
    protected override ValidationResult IsValid(object value, ValidationContext validationContext)
    {
        if (value is int intValue)
        {
            if (intValue <= 0)
            {
                return new ValidationResult(ErrorMessage ?? "Value must be greater than 0.");
            }
        }
        return ValidationResult.Success;
    }
}

Controllers/BikeBuildersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _1FinalCapstone.Models;

namespace _1FinalCapstone.Controllers
{
    public class BikeBuildersController : Controller
    {

        private Entities db = new Entities();

        [Authorize(Roles = "Admin,Owner")]

        public ActionResult Index()
        {
            try
            {
                var build = db.BikeBuilder
                              .Where(bikeBuilder => bikeBuilder.ArchiveStatus != "Archive")
                              .ToList();

                // Filter the data to include only rows with StepTitle starting with 'F' or 'f'
                build = build.Where(bikeBuilder => bikeBuilder.StepTitle != null && bikeBuilder.StepTitle.StartsWith("S", StringComparison.OrdinalIgnoreCase)).ToList();

                foreach (var bikeBuilder in build)
                {
                    if (bikeBuilder.BImage1 != null)
                        bikeBuilder.Budimage1 = Convert.ToBase64String(bikeBuilder.BImage1);

                    if (bikeBuilder.BImage2 != null)
                        bikeBuilder.Budimage2 = Convert.ToBase64String(bikeBuilder.BImage2);

                    if (bikeBuilder.BImage3 != null)
                        bikeBuilder.Budimage3 = Convert.ToBase64String(bikeBuilder.BImage3);
                }

                return View("Index", build);
            }
            catch (Exception ex)
            {
                // Handle or log the exception
                return View("Error"); // Return an error view
            }
        }






        [Authorize(Roles = "Admin,Owner")]

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BikeBuilder bikeBuilder = db.BikeBuilder.Find(id);
            if (bikeBuilder == null)
            {
                return HttpNotFound();
            }

            var viewModel = new BikeBuilder
            {
                BuilderId = bikeBuilder.BuilderId,
                StepTitle = bikeBuilder.StepTitle,
                BuilderTitle1 = bikeBuilder.BuilderTitle1,
                BuilderDescription1 = bikeBuilder.BuilderDescription1,
                Bprice1 = bikeBuilder.Bprice1,
                BuilderTitle2 = bikeBuilder.BuilderTitle2,
                BuilderDescription2 = bikeBuilder.BuilderDescription2,
                Bprice2 = bikeBuilder.Bprice2,
                BuilderTitle3 = bikeBuilder.BuilderTitle3,
                BuilderDescription3 = bikeBuilder.BuilderDescription3,
                Bprice3 = bikeBuilder.Bprice3,
                ArchiveStatus = bikeBuilder.ArchiveStatus
            };

            // Check if an existing image exists and populate the view model
            if (bikeBuilder.BImage1 != null)
            {
                viewModel.BImage1 = bikeBuilder.BImage1;
            }

            if (bikeBuilder.BImage2 != null)
            {
                viewModel.BImage2 = bikeBuilder.BImage2;
            }

            if (bikeBuilder.BImage3 != null)
            {
                viewModel.BImage3 = bikeBuilder.BImage3;
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BikeBuilder bikeBuilder, HttpPostedFileBase BudImage1, HttpPostedFileBase BudImage2, HttpPostedFileBase BudImage3)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        var existingBikeBuilder = db.BikeBuilder.Find(bikeBuilder.BuilderId);
                        if (existingBikeBuilder == null)
                        {
                            return HttpNotFound();
                        }

                        existingBikeBuilder.StepTitle = bikeBuilder.StepTitle;
                        existingBikeBuilder.BuilderTitle1 = bikeBuilder.BuilderTitle1;
                        existingBikeBuilder.BuilderDescription1 = bikeBuilder.BuilderDescription1;
                        existingBikeBuilder.Bprice1 = bikeBuilder.Bprice1;
                        existingBikeBuilder.BuilderTitle2 = bikeBuilder.BuilderTitle2;
                        existingBikeBuilder.BuilderDescription2 = bikeBuilder.BuilderDescription2;
                        existingBikeBuilder.Bprice2 = bikeBuilder.Bprice2;
                        existingBikeBuilder.BuilderTitle3 = bikeBuilder.BuilderTitle3;
                        existingBikeBuilder.BuilderDescription3 = bikeBuilder.BuilderDescription3;
                        existingBikeBuilder.Bprice3 = bikeBuilder.Bprice3;
                        existingBikeBuilder.ArchiveStatus = bikeBuilder.ArchiveStatus;

                        // Only update the image properties if new images are provided
                        if (BudImage1 != null && BudImage1.ContentLength > 0)
                        {
                            var image1Data = new byte[BudImage1.ContentLength];
                            BudImage1.InputStream.Read(image1Data, 0, BudImage1.ContentLength);
                            existingBikeBuilder.BImage1 = image1Data;
                        }

                        if (BudImage2 != null && BudImage2.ContentLength > 0)
                        {
                            var image2Data = new byte[BudImage2.ContentLength];
                            BudImage2.InputStream.Read(image2Data, 0, BudImage2.ContentLength);
                            existingBikeBuilder.BImage2 = image2Data;
                        }

                        if (BudImage3 != null && BudImage3.ContentLength > 0)
                        {
                            var image3Data = new byte[BudImage3.ContentLength];
                            BudImage3.InputStream.Read(image3Data, 0, BudImage3.ContentLength);
                            existingBikeBuilder.BImage3 = image3Data;
                        }

                        db.SaveChanges();
                        transaction.Commit();

                        return RedirectToAction("Index"); // Assuming you have an Index action
                    }
                    catch (DbEntityValidationException ex)
                    {
                        // Handle or log the validation errors
                    }
                    catch (Exception)
                    {
                        // Handle or log the exception
                    }
                }
            }

            // If the ModelState is invalid or an exception occurred, return the view with the provided viewModel
            return View(bikeBuilder);
        }





        // GET: BikeBuilders/Delete/5









        [Authorize(Roles = "Admin,Owner")]

        public ActionResult Index2()
        {
            try
            {
                var build = db.BikeBuilder
                              .Where(bikeBuilder => bikeBuilder.ArchiveStatus != "Archive")
                              .ToList();

                // Filter the data to include only rows with StepTitle starting with 'F' or 'f'
                build = build.Where(bikeBuilder => bikeBuilder.StepTitle != null && bikeBuilder.StepTitle.StartsWith("F", StringComparison.OrdinalIgnoreCase)).ToList();

                foreach (var bikeBuilder in build)
                {
                    if (bikeBuilder.BImage1 != null)
                        bikeBuilder.Budimage1 = Convert.ToBase64String(bikeBuilder.BImage1);

                    if (bikeBuilder.BImage2 != null)
                        bikeBuilder.Budimage2 = Convert.ToBase64String(bikeBuilder.BImage2);

                    if (bikeBuilder.BImage3 != null)
                        bikeBuilder.Budimage3 = Convert.ToBase64String(bikeBuilder.BImage3);
                }

                return View("Index2", build);
            }
            catch (Exception ex)
            {
                // Handle or log the exception
                return View("Error"); // Return an error view
            }
        }


        [Authorize(Roles = "Admin,Owner")]

        public ActionResult Edit2(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BikeBuilder bikeBuilder = db.BikeBuilder.Find(id);
            if (bikeBuilder == null)
            {
                return HttpNotFound();
            }
            var viewModel = new BikeBuilder
            {
                BuilderId = bikeBuilder.BuilderId,
                StepTitle = bikeBuilder.StepTitle,
                BuilderTitle1 = bikeBuilder.BuilderTitle1,
                BuilderDescription1 = bikeBuilder.BuilderDescription1,
                Bprice1 = bikeBuilder.Bprice1,
                BImage1 = bikeBuilder.BImage1,
                ArchiveStatus = bikeBuilder.ArchiveStatus,
                ExistingImageData1 = bikeBuilder.BImage1,
                ExistingImageData2 = bikeBuilder.BImage2,
                ExistingImageData3 = bikeBuilder.BImage3,

            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit2(BikeBuilder bikeBuilder, HttpPostedFileBase BudImage1, HttpPostedFileBase BudImage2, HttpPostedFileBase BudImage3)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        var existingBikeBuilder = db.BikeBuilder.Find(bikeBuilder.BuilderId);
                        if (existingBikeBuilder == null)
                        {

Views/BikeBuilders/Edit.cshtml
@model _1FinalCapstone.Models.BikeBuilder

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<style>
    body {
        background-color: #f8f9fa;
    }

    h4 {
        text-align: center;
    }

    .container {
        margin-top: 10px;
    }

    .form-group {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px #888888;
        padding: 20px;
        margin-bottom: 20px;
    }

    .form-label {
        font-weight: bold;
    }

    input[type="submit"] {
        margin-top: 20px;
    }

    .btn-secondary {
        margin-left: 10px;
    }


    input[type="submit"] {
        margin-top: 10px;
    }

    .btn-secondary {
        margin-left: 0px;
        margin-top: 10px;
    }
</style>
<center>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">

                @using (Html.BeginForm("Edit", "BikeBuilders", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">

                        <h2 class="text-center mb-4"><b>Edit Bike Details</b></h2>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.BuilderId)
                    <center>

                        Step Title
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StepTitle, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StepTitle, "", new { @class = "text-danger" })
                        </div>

                        Builder Title
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.BuilderTitle1, new { @class = "form-control", @rows = 3 })
                            @Html.ValidationMessageFor(model => model.BuilderTitle1, "", new { @class = "text-danger" })
                        </div>


                        Builder Description
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.BuilderDescription1, new { @class = "form-control", @rows = 8 })
                            @Html.ValidationMessageFor(model => model.BuilderDescription1, "", new { @class = "text-danger" })
                        </div>

                        Price
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Bprice1, new { htmlAttributes = new { @class = "form-control", @min = 1, @oninput = "validateInput(this);" } })
                            @Html.ValidationMessageFor(model => model.Bprice1, "", new { @class = "text-danger" })
                        </div>



                        <div class="mb-3">
                            @if (Model.ExistingImageData1 != null)
                            {
                                <img src="data:image/png;base64,@Convert.ToBase64String(Model.ExistingImageData1)" class="img-thumbnail" style="max-width: 200px; max-height: 200px;" />
                            }
                            else if (Model.BImage1 != null)
                            {
                                <img src="data:image/png;base64,@Convert.ToBase64String(Model.BImage1)" class="img-thumbnail" style="max-width: 200px; max-height: 200px;" />
                            }
                            else
                            {
                                <span>No image available</span>
                            }
                        </div>


                        <div class="mb-3">
                            <input type="file" class="form-control-file" id="BImage1" name="BudImage1" accept=".png, .jpg, .jpeg" />
                        </div>
                        <span id="ImageValidation" class="text-danger validation-error"></span>
                        <br />

                        Archive Status
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.ArchiveStatus, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.ArchiveStatus, "", new { @class = "text-danger" })
                        </div>

                    </center>


                        <div class="mb-3 text-center">
                            <input type="submit" value="Save Changes" class="btn btn-primary" />
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
                        </div>
                    </div>

                }
            </div>
        </div>

    </div>
</center>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('form').submit(function (event) {
                var imageInput = $('#BImage1');
                var imageValidation = $('#ImageValidation');

                // Check if the image input is empty
                if (imageInput.val() === '') {

                } else {
                    // Check the file extension
                    var fileName = imageInput.val();
                    var fileExtension = fileName.substr((fileName.lastIndexOf('.') + 1));

                    if (fileExtension.toLowerCase() !== 'png' && fileExtension.toLowerCase() !== 'jpg' && fileExtension.toLowerCase() !== 'jpeg') {
                        event.preventDefault(); // Prevent form submission
                        imageValidation.text('Please select a PNG, JPG, or JPEG image.'); // Display error message
                    } else {
                        imageValidation.text(''); // Clear any previous error message
                    }
                }
            });
            // Block negative, positive signs, and leading zeros on keydown
            $('input[type="number"]').on('keydown', function (e) {
                if (e.key === '-' || e.key === '+' || (e.key === '0' && this.value.length === 0)) {
                    e.preventDefault();
                }
            });
        });
    </script>


}

Views/BikeBuilders/Edit2.cshtml
@model _1FinalCapstone.Models.BikeBuilder

@{
    ViewBag.Title = "Edit2";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<style>
    body {
        background-color: #f8f9fa;
    }

    h4 {
        text-align: center;
    }

    .container {
        margin-top: 10px;
    }

    .form-group {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px #888888;
        padding: 20px;
        margin-bottom: 20px;
    }

    .form-label {
        font-weight: bold;
    }

    input[type="submit"] {
        margin-top: 20px;
    }

    .btn-secondary {
        margin-left: 10px;
    }


    input[type="submit"] {
        margin-top: 10px;
    }

    .btn-secondary {
        margin-left: 0px;
        margin-top: 10px;
    }
</style>
<center>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <br />

                @using (Html.BeginForm("Edit2", "BikeBuilders", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <h2 class="text-center mb-4"><b>Edit Bike Details</b></h2>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.BuilderId)
                    <center>

                        Step Title
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StepTitle, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StepTitle, "", new { @class = "text-danger" })
                        </div>

                        Builder Title
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.BuilderTitle1, new { @class = "form-control", @rows = 3 })
                            @Html.ValidationMessageFor(model => model.BuilderTitle1, "", new { @class = "text-danger" })
                        </div>


                        Builder Description
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.BuilderDescription1, new { @class = "form-control", @rows = 12 })
                            @Html.ValidationMessageFor(model => model.BuilderDescription1, "", new { @class = "text-danger" })
                        </div>

                        Price
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Bprice1, new { htmlAttributes = new { @class = "form-control", @min = 1, @oninput = "validateInput(this);" } })
                            @Html.ValidationMessageFor(model => model.Bprice1, "", new { @class = "text-danger" })
                        </div>

                        <br />
                        <div class="mb-3">
                            @if (Model.ExistingImageData1 != null)
                            {
                                <img src="data:image/png;base64,@Convert.ToBase64String(Model.ExistingImageData1)" class="img-thumbnail" style="max-width: 200px; max-height: 200px;" />
                            }
                            else if (Model.BImage1 != null)
                            {
                                <img src="data:image/png;base64,@Convert.ToBase64String(Model.BImage1)" class="img-thumbnail" style="max-width: 200px; max-height: 200px;" />
                            }
                            else
                            {
                                <span>No image available</span>
                            }
                        </div>

                        <div class="mb-3">
                            <input type="file" class="form-control-file" id="BImage1" name="BudImage1" accept=".png, .jpg, .jpeg" />
                            <br />
                            <span id="ImageValidation" class="text-danger validation-error"></span>
                        </div>
                        <br />
                    </center>

                        Archive Status
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.ArchiveStatus, new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.ArchiveStatus, "", new { @class = "text-danger" })
                        </div>

                        <div class="mb-3 text-center">
                            <input type="submit" value="Save Changes" class="btn btn-primary" />
                            @Html.ActionLink("Back to List", "Index2", null, new { @class = "btn btn-secondary" })
                        </div>
                    </div>

                }
            </div>
        </div>

    </div>
</center>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            $('form').submit(function (event) {
                var imageInput = $('#BImage1');
                var imageValidation = $('#ImageValidation');

                // Check if the image input is empty
                if (imageInput.val() === '') {

                } else {
                    // Check the file extension
                    var fileName = imageInput.val();
                    var fileExtension = fileName.substr((fileName.lastIndexOf('.') + 1));

                    if (fileExtension.toLowerCase() !== 'png' && fileExtension.toLowerCase() !== 'jpg' && fileExtension.toLowerCase() !== 'jpeg') {
                        event.preventDefault(); // Prevent form submission
                        imageValidation.text('Please select a PNG, JPG, or JPEG image.'); // Display error message
                    } else {
                        imageValidation.text(''); // Clear any previous error message
                    }
                }
            });
            // Block negative, positive signs, and leading zeros on keydown
            $('input[type="number"]').on('keydown', function (e) {
                if (e.key === '-' || e.key === '+' || (e.key === '0' && this.value.length === 0)) {
                    e.preventDefault();
                }
            });
        });
    </script>
}

Views/BikeBuilders/Index.cshtml
@model  IEnumerable<_1FinalCapstone.Models.BikeBuilder>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}


<style>
    .btn-margin {
        margin-left: 10px;
    }

    table.table thead th {
        width: 10%; /* Adjust the width as needed */
        white-space: nowrap; /* Prevent text from wrapping */
        overflow: hidden; /* Hide overflowing text */
        text-overflow: ellipsis; /* Add ellipsis (...) for long titles */
    }
</style>

<br />
<h2 class="text-center mb-4"><b> Step Bike Builder</b></h2>
<div class="d-flex justify-content-end mb-2">

    <!-- Button to redirect to Index2 with increased margin -->
    @Html.ActionLink("Go to Bike Final Creation", "Index2", null, new { @class = "btn btn-success btn-margin" })



</div>
<div class="table-responsive">
    <div class="mb-2">
        <input type="text" id="searchInput" class="form-control" placeholder="Search by Name" />
    </div>
    <div class="mb-2" style="background-color: #f7f7f7; border: 1px solid #ccc; padding: 10px; border-radius: 5px;">
        <p style="font-weight: bold;">Choose Category to get Started</p>
        <select id="categoryDropdown">
            <option value="" selected>All</option>
            <option value="Step 1">Step 1</option>
            <option value="Step 2">Step 2</option>
            <option value="Step 3">Step 3</option>
            <option value="Step 4">Step 4</option>
            <option value="Step 5">Step 5</option>

        </select>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Step Title</th>
                <th>Builder Title 1</th>
                <th>Builder Description 1</th>
                <th>Price</th>
                <th>Image</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>


            @foreach (var item in Model)
            {
                <tr class="product-row">
                    <td>
                        @Html.DisplayFor(modelItem => item.StepTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BuilderTitle1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BuilderDescription1)
                    </td>
                    <td>
                        ₱@string.Format("{0:n0}", item.Bprice1).00
                    </td>
                    <td>
                        <img src="data:image/png;base64,@item.Budimage1" class="img-thumbnail" style="max-width: 200px; max-height: 200px;" />
                    </td>

                    @*<td>
                            <img src="data:image/png;base64,@item.Budimage2" class="img-thumbnail" style="max-width: 200px; max-height: 200px;" />
                        </td>*@



                    <td>
                        <a href="@Url.Action("Edit", new { id = item.BuilderId })" class="btn btn-primary btn-sm">
                            <i class="far fa-edit fa-lg"></i> <span class="ml-2">Edit</span>
                        </a>



                    </td>


                </tr>
            }
    </table>
</div>

@section scripts {


    <script>
            $(document).ready(function () {
                // Function to filter the table rows based on the selected category
                $("#categoryDropdown").change(function () {
                    var selectedCategory = $(this).val();

                    // Store the selected category in local storage
                    localStorage.setItem("selectedCategory", selectedCategory);

                    // Hide all rows
                    $(".product-row").hide();

                    if (selectedCategory === "All") {
                        $(".product-row").show();
                    } else {
                        // Find the correct column index for "Step Title" - adjust if necessary
                        var columnIndex = findStepTitleColumnIndex();
                        if (columnIndex >= 0) {
                            $(".product-row:has(td:eq(" + columnIndex + "):contains('" + selectedCategory + "'))").show();
                        }
                    }
                });

                // Function to filter the table rows based on the search input
                $("#searchInput").on("keyup", function () {
                    var value = $(this).val().toLowerCase();
                    $(".product-row").filter(function () {
                        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
                    });
                });

                // Function to confirm archiving an item

                // Retrieve and set the selected category from local storage
                var selectedCategory = localStorage.getItem("selectedCategory");
                if (selectedCategory) {
                    $("#categoryDropdown").val(selectedCategory);
                    // Trigger the change event to apply the filter
                    $("#categoryDropdown").change();
                }

                // Helper function to find the column index for "Step Title"
                function findStepTitleColumnIndex() {
                    var stepTitle = "Step Title"; // Update with the actual text in the table header
                    var headers = $("thead th");
                    for (var i = 0; i < headers.length; i++) {
                        if ($(headers[i]).text().trim() === stepTitle) {
                            return i;
                        }
                    }
                    return -1; // Step Title not found
                }
            });
    </script>

    <script>
            $(document).ready(function () {
                // When the search input changes, filter the table rows.
                $('#searchInput').on('input', function () {
                    var searchText = $(this).val().toLowerCase();
                    $('.table tbody tr').each(function () {
                        var rowText = $(this).text().toLowerCase();
                        $(this).toggle(rowText.indexOf(searchText) > -1);
                    });
                });
            });
            function confirmArchive(button) {
                if (confirm("Are you sure you want to archive this item?")) {
                    // If the user confirms, submit the form
                    button.closest("form").submit();
                } else {
                    // If the user cancels, do nothing
                }
            }
    </script>
}