Models/CartBuilder.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartBuilder
    {
        public int CartBuilderId { get; set; }
        public string Email { get; set; }
        public Nullable<int> BuilderId { get; set; }
        public string BuilderName { get; set; }
        public Nullable<int> BuilderPrice { get; set; }
        public Nullable<int> QuantityBuilder { get; set; }
        public Nullable<int> SubtotalBuilder { get; set; }
        public byte[] BuilderImage { get; set; }
    }
}

Controllers/CustomerBuilderController.cs
using _1FinalCapstone.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace _1FinalCapstone.Controllers
{
    public class CustomerBuilderController : Controller
    {
        private Entities db = new Entities();
        // GET: CustomerBuilder
        //[Authorize(Roles = "Admin, Customer")]

      

        public ActionResult BuilderMain()
        {
            try
            {
                var build = db.BikeBuilder.ToList();

                foreach (var bikeBuilder in build)
                {
                    if (bikeBuilder.BImage1 != null)
                        bikeBuilder.Budimage1 = Convert.ToBase64String(bikeBuilder.BImage1);

                    if (bikeBuilder.BImage2 != null)
                        bikeBuilder.Budimage2 = Convert.ToBase64String(bikeBuilder.BImage2);

                    if (bikeBuilder.BImage3 != null)
                        bikeBuilder.Budimage3 = Convert.ToBase64String(bikeBuilder.BImage3);
                }

                var mergeModel = new Merge
                {
                    BikeBuilders = build
                };

                return View(mergeModel);
            }
            catch (Exception ex)
            {
                // Handle or log the exception
                return View("Error"); // Return an error view
            }
        }

        public ActionResult GetPartialView(int builderId)
        {
            // Define a list of Builder IDs for each case
            List<int> selectedBuilderIdsForPartial1 = new List<int> { 3, 4, };
            List<int> selectedBuilderIdsForPartial2 = new List<int> { 5, 6, };


            List<int> selectedBuilderIds;

            switch (builderId)
            {
                case 1:
                    selectedBuilderIds = selectedBuilderIdsForPartial1;
                    break;
                case 2:
                    selectedBuilderIds = selectedBuilderIdsForPartial2;
                    break;

                default:
                    return Content("Invalid builder selection");
            }

            // Fetch data for the selected Builder IDs
            var builderData = db.BikeBuilder.Where(b => selectedBuilderIds.Contains(b.BuilderId)).ToList();

            foreach (var bikeBuilder in builderData)
            {
                if (bikeBuilder.BImage1 != null)
                    bikeBuilder.Budimage1 = Convert.ToBase64String(bikeBuilder.BImage1);

                if (bikeBuilder.BImage2 != null)
                    bikeBuilder.Budimage2 = Convert.ToBase64String(bikeBuilder.BImage2);

                if (bikeBuilder.BImage3 != null)
                    bikeBuilder.Budimage3 = Convert.ToBase64String(bikeBuilder.BImage3);
            }

            // Create a model and return the appropriate partial view
            var mergeModel = new Merge
            {
                BikeBuilders = builderData
            };

            switch (builderId)
            {
                case 1:
                    return PartialView("_BuilderIds34", mergeModel);
                case 2:
                    return PartialView("_BuilderIds56", mergeModel);

                default:
                    return Content("Invalid builder selection");
            }
        }



        public ActionResult LoadPartialView(int builderId)
        {
            // Define a list of Builder IDs for each case
            List<int> selectedBuilderIdsForPartial1 = new List<int> { 7, 8 };
            List<int> selectedBuilderIdsForPartial2 = new List<int> { 9, 10 };

            List<int> selectedBuilderIds;

            switch (builderId)
            {

                case 3:
                    // For builderId 3, show Builder IDs 7 and 8 in the partial view
                    selectedBuilderIds = new List<int> { 7, 8 };
                    break;
                case 4:
                    // For builderId 3, show Builder IDs 7 and 8 in the partial view
                    selectedBuilderIds = new List<int> { 9, 10 };
                    break;
                case 5:
                    // For builderId 3, show Builder IDs 7 and 8 in the partial view
                    selectedBuilderIds = new List<int> { 11, 12 };
                    break;
                case 6:
                    // For builderId 3, show Builder IDs 7 and 8 in the partial view
                    selectedBuilderIds = new List<int> { 13, 14 };
                    break;


                default:
                    return Content("Invalid builder selection");
            }

            // Fetch data for the selected Builder IDs
            var builderData = db.BikeBuilder.Where(b => selectedBuilderIds.Contains(b.BuilderId)).ToList();

            foreach (var bikeBuilder in builderData)
            {
                if (bikeBuilder.BImage1 != null)
                    bikeBuilder.Budimage1 = Convert.ToBase64String(bikeBuilder.BImage1);

                if (bikeBuilder.BImage2 != null)
                    bikeBuilder.Budimage2 = Convert.ToBase64String(bikeBuilder.BImage2);

                if (bikeBuilder.BImage3 != null)
                    bikeBuilder.Budimage3 = Convert.ToBase64String(bikeBuilder.BImage3);
            }

            // Create a model and return the appropriate partial view
            var mergeModel = new Merge
            {
                BikeBuilders = builderData
            };

            switch (builderId)
            {

                case 3:
                    return PartialView("_BuilderIds78", mergeModel); // Display Builder IDs 7 and 8 for builderId 3
                case 4:
                    return PartialView("_BuilderIds910", mergeModel); // Display Builder IDs 7 and 8 for builderId 3
                case 5:
                    return PartialView("_BuilderIds1112", mergeModel); // Display Builder IDs 7 and 8 for builderId 3
                case 6:
                    return PartialView("_BuilderIds1314", mergeModel); // Display Builder IDs 7 and 8 for builderId 3

                default:
                    return Content("Invalid builder selection");
            }
        }




        public ActionResult LoadPartialView1(int builderId)
        {
            List<int> selectedBuilderIds;

            switch (builderId)
            {
                case 7:
                    // For builderId 7, show Builder IDs 15 and 16 in the partial view
                    selectedBuilderIds = new List<int> { 15, 16 };
                    break;
                case 8:
                    // For builderId 8, show Builder IDs 17 and 18 in the partial view
                    selectedBuilderIds = new List<int> { 17, 18 };
                    break;
                case 9:
                    // For builderId 7, show Builder IDs 15 and 16 in the partial view
                    selectedBuilderIds = new List<int> { 19, 20 };
                    break;
                case 10:
                    // For builderId 8, show Builder IDs 17 and 18 in the partial view
                    selectedBuilderIds = new List<int> { 21, 22 };
                    break;



                default:
                    return Content("Invalid builder selection");
            }

            // Fetch data for the selected Builder IDs
            var builderData = db.BikeBuilder.Where(b => selectedBuilderIds.Contains(b.BuilderId)).ToList();

            foreach (var bikeBuilder in builderData)
            {
                if (bikeBuilder.BImage1 != null)
                    bikeBuilder.Budimage1 = Convert.ToBase64String(bikeBuilder.BImage1);

                if (bikeBuilder.BImage2 != null)
                    bikeBuilder.Budimage2 = Convert.ToBase64String(bikeBuilder.BImage2);

                if (bikeBuilder.BImage3 != null)
                    bikeBuilder.Budimage3 = Convert.ToBase64String(bikeBuilder.BImage3);
            }

            // Create a model and return the appropriate partial view
            var mergeModel = new Merge
            {
                BikeBuilders = builderData
            };

            switch (builderId)
            {
                case 7:
                    return PartialView("_BuilderIds1516", mergeModel); // Display Builder IDs 15 and 16 for builderId 7
                case 8:
                    return PartialView("_BuilderIds1718", mergeModel); // Display Builder IDs 17 and 18 for builderId 8
                case 9:
                    return PartialView("_BuilderIds1920", mergeModel); // Display Builder IDs 15 and 16 for builderId 7
                case 10:
                    return PartialView("_BuilderIds2122", mergeModel); // Display Builder IDs 17 and 18 for builderId 8

                default:
                    return Content("Invalid builder selection");
            }
        }
        public ActionResult LoadPartialView2(int builderId)
        {
            List<int> selectedBuilderIds;

            switch (builderId)
            {
                case 11:
                    // For builderId 7, show Builder IDs 15 and 16 in the partial view
                    selectedBuilderIds = new List<int> { 23, 24 };
                    break;
                case 12:
                    // For builderId 8, show Builder IDs 17 and 18 in the partial view
                    selectedBuilderIds = new List<int> { 25, 26 };
                    break;
                case 13:
                    // For builderId 7, show Builder IDs 15 and 16 in the partial view
                    selectedBuilderIds = new List<int> { 27, 28 };
                    break;
                case 14:
                    // For builderId 8, show Builder IDs 17 and 18 in the partial view
                    selectedBuilderIds = new List<int> { 29, 30 };
                    break;



                default:

Views/CustomerBuilder/Final2.cshtml
@model IEnumerable<_1FinalCapstone.Models.BikeBuilder>

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Final 2</title>
    <!-- Add any necessary CSS or meta tags here -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="~/css/StyleSheet2.css" rel="stylesheet" />

</head>
<body>
    @foreach (var item in Model)
    {
        <div class="container py-4 my-4 mx-auto d-flex flex-column">
            <div class="header">
                <div class="row r1">
                    <div class="col-md-9 abc">

                        <h1> @Html.DisplayFor(modelItem => item.BuilderTitle1)</h1>
                    </div>


                </div>
            </div>
            <div class="container-body mt-4">
                <div class="row r3">
                    <div class="col-md-5 p-0 klo">
                        <ul>


                            <li>@Html.DisplayFor(modelItem => item.BuilderDescription1)</li>
                            <li>  <b> @Html.DisplayFor(modelItem => item.Bprice1)₱</b></li>

                        </ul>

                    </div>
                    <div class="col-md-7">
                        <img data-image="red" class="active" src="data:image/png;base64,@item.Budimage1" width="90%" height="95%" alt="">
                    </div>
                </div>
            </div>

            <div class="footer d-flex flex-column mt-5">
                <div class="row r4">
                    <div class="col-md-2 myt ">
                        <button type="button" class="btn btn-info btn-lg" id="return-btn">
                            <a href="Step2Fork3" class="btn btn-info btn-lg" id="return-btn">
                                <i class="fas fa-arrow-left"></i> Go Back
                            </a>
                        </button>
                    </div>


                    <!-- Replace this button code -->
                    <div class="col-md-2 myt">
                        <form method="post" action="@Url.Action("AddToBuilder", "CustomerBuilder")">
                            <input type="hidden" name="builderId" value="@item.BuilderId" />
                            <button type="submit" class="btn btn-primary add-to-cart" style="font-size: 1rem;">Add to Cart</button>
                        </form>
                    </div>



                </div>
            </div>
        </div>
    }
</body>
</html>

Views/CustomerBuilder/_BuilderDataPartial.cshtml
@model _1FinalCapstone.Models.Merge

@if (Model.BikeBuilders.Any())
{
    var builder1 = Model.BikeBuilders.FirstOrDefault(b => b.BuilderId == Model.BuilderId1);
    var builder2 = Model.BikeBuilders.FirstOrDefault(b => b.BuilderId == Model.BuilderId2);
    var builder3 = Model.BikeBuilders.FirstOrDefault(b => b.BuilderId == Model.BuilderId3);
    var builder4 = Model.BikeBuilders.FirstOrDefault(b => b.BuilderId == Model.BuilderId4);
    var builder5 = Model.BikeBuilders.FirstOrDefault(b => b.BuilderId == Model.BuilderId5);
    var builder6 = Model.BikeBuilders.FirstOrDefault(b => b.BuilderId == Model.BuilderId6);


    var commonBuilderT = builder1; // Use Builder3 if available, otherwise use Builder5
    var commonBuilderY = builder2; // Use Builder4 if available, otherwise use Builder6
    var commonBuilder1 = builder3 ?? builder5; // Use Builder3 if available, otherwise use Builder5
    var commonBuilder2 = builder4 ?? builder6; // Use Builder4 if available, otherwise use Builder6



    if (commonBuilder1 != null)
    {
        <div class="builder" data-builderid="3">
            <h2>@commonBuilder1.StepTitle</h2>
            <h3>@commonBuilder1.BuilderTitle1</h3>
            <p>@commonBuilder1.BuilderDescription1</p>
            <p>Price: $@commonBuilder1.Bprice1</p>

            @if (!string.IsNullOrEmpty(commonBuilder1.Budimage1))
            {
                <!-- Apply the small-image class to make the image smaller -->
                <img src="data:image/jpeg;base64, @commonBuilder1.Budimage1" alt="Image 1" class="small-image" />
            }
            <!-- Radio Buttons -->

        </div>
    }

    if (commonBuilder2 != null)
    {
        <div class="builder" data-builderid="4">
            <h2>@commonBuilder2.StepTitle</h2>
            <h3>@commonBuilder2.BuilderTitle1</h3>
            <p>@commonBuilder2.BuilderDescription1</p>
            <p>Price: $@commonBuilder2.Bprice1</p>

            @if (!string.IsNullOrEmpty(commonBuilder2.Budimage1))
            {
                <!-- Apply the small-image class to make the image smaller -->
                <img src="data:image/jpeg;base64, @commonBuilder2.Budimage1" alt="Image 1" class="small-image" />
            }
            <!-- Radio Buttons -->

        </div>
    }

    <form>
        <label>
            <input type="radio" name="builderSelection" value="1" checked /> Builder 3 and 5
        </label>
        <label>
            <input type="radio" name="builderSelection" value="2" /> Builder 4 and 6
        </label>
        <input type="button" value="Load Data" id="loadDataButton" />
    </form>

    <!-- "Go Back" Button -->
    <input type="button" value="Go Back to Builder 1 and 2" id="goBackToBuilder1And2Button" />


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
        $(document).ready(function () {
            // Function to hide/show builder divs based on the selected radio button
            function toggleBuilderDivs(selectedBuilder) {
                // Hide all builder divs except Builder 1 and Builder 2

                $('.builder').hide();
                if (selectedBuilder === '1') {
                    // Show Builder 3 and 5 when the first radio button is selected
                    $('.builder[data-builderid="3"]').show();
                    $('.builder[data-builderid="5"]').show();
                } else if (selectedBuilder === '2') {
                    // Show Builder 4 and 6 when the second radio button is selected
                    $('.builder[data-builderid="4"]').show();
                    $('.builder[data-builderid="6"]').show();
                }
            }

            // Handle radio button change event
            $('input[name="builderSelection"]').change(function () {
                var selectedBuilder = $(this).val();
                // Toggle builder divs to show/hide based on the selected radio button
                toggleBuilderDivs(selectedBuilder);
            });

            // Initially hide all builder divs except the ones with data-builderid equal to 3 and 5 (Builder 3 and 5)
            $('.builder').hide();
            $('.builder[data-builderid="3"]').show();
            $('.builder[data-builderid="5"]').show();

            // Set the initially selected radio button to "Builder 3 and 5"
            $('input[name="builderSelection"][value="1"]').prop('checked', true);

            // Handle form submission (optional)
            $('#loadDataButton').click(function (e) {
                e.preventDefault(); // Prevent the default form submission behavior
                var selectedBuilder = $('input[name="builderSelection"]:checked').val();
                // You can perform AJAX data loading here if needed
            });


        });
    </script>
    <script>
      

        $(document).ready(function () {
            // Event handler for "Go Back" button click
            $('#goBackToBuilder1And2Button').click(function () {
                // Hide the partial view container
                $('#builderData').hide();
                // Show the main content container
                $('#mainContent').show();
                $('#builderM').show();
               
            });
        });
    </script>
    
}
else
{
    <p>No data available for the selected builder.</p>
}

Views/CustomerBuilder/_BuilderIds4142.cshtml
@model _1FinalCapstone.Models.Merge

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Builder Data</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Oswald', sans-serif;
            overflow: hidden;
        }

        .left-section {
            flex: 1;
            margin-left: -250px;
        }

        .right-section {
            width: 300px; /* Adjust the width as needed */
            position: relative;
            right: 50px;
        }

        .builderM {
            color: black;
            position: relative;
            left: 200px;
        }

            .builderM img {
                position: relative;
                max-width: 45%;
                max-height: 45%;
                margin-left: auto; /* Move the image to the right by setting margin-left to auto */
                left: 160px; /* Optional: If you want to further adjust the position to the right */
            }


            .builderM h2 {
                margin-left: 70px;
                position: relative;
                top: -80px;
                font-size: 30px;
                color: black; /* Set the text color */
                /* Add other font styles like text-decoration, font-weight, etc. */
            }

            .builderM h3 {
                margin-left: 70px;
                position: relative;
                top: -80px;
                font-size: 30px;
                color: black;
            }

            .builderM p {
                margin-left: 70px;
                position: relative;
                top: -80px;
                font-size: 20px;
                color: black;
            }

                .builderM p.price {
                    margin-left: 70px;
                    position: relative;
                    top: -80px;
                    font-size: 27px;
                    color: black; /* Custom color for price */
                    font-weight: bold;
                }

        /* Add these styles to display radio buttons side by side */
        .form-check {
            display: inline-block; /* Change to inline-block for side-by-side display */
            margin-left: 20px; /* Adjust margin as needed to separate radio buttons */
        }

        .custom-inline {
            display: inline-block;
            margin-left: 20px; /* Adjust margin as needed to separate radio buttons */
        }

        .blackbg {
            background-image: url('../../whitebg.jpg');
            background-size: cover; /* Ensures the image covers the entire viewport */
            background-repeat: no-repeat; /* Prevents the image from repeating */
            background-attachment: fixed; /* Optional: Keeps the image fixed while scrolling */
        }

        .rounded-container {
            width: 60%; /* Adjust the width as needed */
            margin: 0 auto; /* Center the container horizontally */
            border-radius: 10px; /* Adjust the value to control the roundness */
            background-color: rgb(128, 128, 128, .5); /* Adjust the background color and opacity */
            padding: 20px; /* Add padding to create space inside the container */
            position: relative; /* Position relative to move it */
            right: 250px;
            bottom: 650px; /* Adjust the top value to move it lower */
        }
    </style>
</head>

<body>
    <div class="blackbg" />
    <div id="5thpartialContent">
        <div id="mainContent" class="container">
            <div class="col-lg-12 col-md-12">
                @foreach (var bikeBuilder in Model.BikeBuilders)
                {
                    if (bikeBuilder.BuilderId == 41 || bikeBuilder.BuilderId == 42)
                    {
                        <div class="builderM" data-builderid="@bikeBuilder.BuilderId">

                            @if (!string.IsNullOrEmpty(bikeBuilder.Budimage1))
                            {
                                <!-- Apply the small-image class to make the image smaller -->
                                <img src="data:image/jpeg;base64, @bikeBuilder.Budimage1" alt="Image 3" class="img-fluid"/>
                            }
                        </div>
                      
                        <div class="builderM mb-4" data-builderid="@bikeBuilder.BuilderId">
                            <br />
                            <h2>@bikeBuilder.StepTitle</h2>
                            <h3>@bikeBuilder.BuilderTitle1</h3><br />
                            <p>@bikeBuilder.BuilderDescription1</p>
                            <p>Price: ₱@bikeBuilder.Bprice1</p>
                        </div>
                    }
                }
                
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="rounded-container">
                    <div id="builder34Buttons">
                        <form method="post" action="@Url.Action("FinalStep", "CustomerBuilder")">



                            <div class="form-check custom-inline">

                                @{
                                    var builder1Image1 = Model.BikeBuilders.FirstOrDefault(bikeBuilder => bikeBuilder.BuilderId == 41);
                                }
                                @if (builder1Image1 != null && !string.IsNullOrEmpty(builder1Image1.Budimage1))
                                {
                                    <img src="data:image/jpeg;base64, @builder1Image1.Budimage1" alt="Image 1" class="img-fluid" />
                                }
                                <input type="radio" class="form-check-input" name="builderSelection6" value="41" checked />
                                <label class="form-check-label">Handlebar 1</label>


                                @{
                                    var builder1Image2 = Model.BikeBuilders.FirstOrDefault(bikeBuilder => bikeBuilder.BuilderId == 42);
                                }
                                @if (builder1Image2 != null && !string.IsNullOrEmpty(builder1Image2.Budimage1))
                                {
                                    <img src="data:image/jpeg;base64, @builder1Image2.Budimage1" alt="Image 1" class="img-fluid" />
                                }
                                <input type="radio" class="form-check-input" name="builderSelection6" value="42" />
                                <label class="form-check-label">Handlebar 2</label>
                            </div>

                            <input type="submit" class="btn btn-primary mt-2" value="Final Step" />
                            <input type="button" class="btn btn-primary mt-2" value="Go Back" id="loadDataButton6" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="partialViewContainer1"></div>
    <script>
        $(document).ready(function () {
            // Function to hide/show builder divs based on the selected radio button
            function toggleBuilderDivs(selectedBuilder) {
                $('.builderM').hide(); // Hide all builder divs
                $('.builderM[data-builderid="' + selectedBuilder + '"]').show(); // Show the selected builder div
            }

            // Function to initialize the page with the initially checked radio button
            function initializePage() {
                // Handle radio button change event
                $('input[name="builderSelection6"]').change(function () {
                    var selectedBuilder = $(this).val();

                    // Toggle builder divs to show/hide based on the selected radio button
                    toggleBuilderDivs(selectedBuilder);
                });

                // Initially hide all builder divs except the one corresponding to BuilderId 7 (since it's checked)
                toggleBuilderDivs(41);
            }

            // Function to load the partial view
            function loadPartialView(builderId) {
                // Hide various elements on the page
                $('input[name="builderSelection6"]').hide();
                $('#loadDataButton6').hide();
                $('#goBackButton').hide();
                $('#4thpartialContent').hide(); // Changed the ID to match the HTML

                // Hide all .builderM elements
                $('.builderM').hide();

                var partialViewUrl = "/CustomerBuilder/LoadPartialView3?builderId=" + builderId;

                $.ajax({
                    url: partialViewUrl,
                    type: "GET",
                    success: function (data) {
                        $("#partialViewContainer1").html(data);
                    },
                    error: function () {
                        alert("Failed to load partial view.");
                    }
                });
            }

            // Handle button click event to load the partial view
            $('#loadDataButton6').click(function () {
                var selectedBuilder = $('input[name="builderSelection6"]:checked').val();

                // Load the partial view
                loadPartialView(selectedBuilder);
            });

            // Call the initialization function when the document is ready
            initializePage();
        });
    </script>