Models/AspNetUsers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUsers()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaims>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogins>();
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        [Required]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "The ContactNumber must be exactly 11 characters.")]
        public string ContactNumber { get; set; }
        [Required]
        public string Address { get; set; }
        public string AccountStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}

Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _1FinalCapstone.Models;

namespace _1FinalCapstone.Controllers
{
    public class AspNetUsersController : Controller
    {
        private Entities db = new Entities();

        // GET: AspNetUsers
        [Authorize(Roles = "Owner")]
        public ActionResult Index()
        {
            // Get all users from the database
            var allUsers = db.AspNetUsers.ToList();

            // Filter the users with AccountStatus "Disable"
            var filteredUsers = allUsers.Where(user => user.AccountStatus != "Disable").ToList();

            return View(filteredUsers);
        }

        [Authorize(Roles = "Owner")]
        public ActionResult DisableAccounts()
        {
            // Get all users from the database
            var allUsers = db.AspNetUsers.ToList();

            // Filter the users with AccountStatus "Disable"
            var disabledUsers = allUsers.Where(user => user.AccountStatus == "Disable").ToList();

            return View(disabledUsers);
        }

        public ActionResult ManageAccount()
        {
            string userEmail = User.Identity.Name;

            var user = db.AspNetUsers.FirstOrDefault(u => u.Email == userEmail);

            if (user != null)
            {
                // Retrieve the user's cart and cart builder information
                var cart = db.Cart.Where(c => c.Email == userEmail).ToList();
                var cartBuilder = db.CartBuilder.Where(cb => cb.Email == userEmail).ToList();
                var products = db.Product.ToList();

                // Create a view model to combine the user and cart information
                var viewModel = new Merge
                {
                    Cart = cart,
                    CartBuilder = cartBuilder,
                    // You can add more properties to the viewModel as needed
                };

                var userCollection = new List<AspNetUsers> { user };
                ViewBag.Products = products; // You can use ViewBag to pass data to the view

                return View(userCollection);
            }
            else
            {
                // Handle the case where the user's data is not found
                return View("NotFoundView");
            }
        }


        // GET: AspNetUsers/Details/5
     

        // GET: AspNetUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] AspNetUsers aspNetUsers)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUsers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUsers);
        }

        // GET: AspNetUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUsers aspNetUsers = db.AspNetUsers.Find(id);
            if (aspNetUsers == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUsers);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,LockoutEnabled,FirstName,LastName,CreateDate,Address,ContactNumber,UserName")] AspNetUsers aspNetUsers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUsers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetUsers);
        }

        // GET: AspNetUsers/Edit/5
        public ActionResult EditAccount(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUsers aspNetUsers = db.AspNetUsers.Find(id);
            if (aspNetUsers == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUsers);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAccount([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,LockoutEnabled,FirstName,LastName,CreateDate,Address,ContactNumber,UserName")] AspNetUsers aspNetUsers)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the existing user from the database
                var existingUser = db.AspNetUsers.Find(aspNetUsers.Id);
                if (existingUser == null)
                {
                    return HttpNotFound();
                }

                // Capture the old values
                var oldFirstName = existingUser.FirstName;
                var oldLastName = existingUser.LastName;
                var oldAddress = existingUser.Address;
                var oldContactNumber = existingUser.ContactNumber;

                // Update the properties you want to change
                existingUser.FirstName = aspNetUsers.FirstName;
                existingUser.LastName = aspNetUsers.LastName;
                existingUser.Address = aspNetUsers.Address;
                existingUser.ContactNumber = aspNetUsers.ContactNumber;

                // Retrieve the existing AuditLogs record for the user
                var auditLog = db.AuditLogs.FirstOrDefault(a => a.Email == existingUser.Email);

                if (auditLog != null)
                {
                    // Update the properties of the existing AuditLogs record
                    auditLog.FirstName = existingUser.FirstName;
                    auditLog.LastName = existingUser.LastName;
                    auditLog.ContactNumber = existingUser.ContactNumber;
                    auditLog.Address = existingUser.Address;
                    auditLog.ChangeBasicInfoDate = DateTime.Now; // Set the ChangeBasicInfoDate to the current date and time

                    // Set the old values
                    auditLog.OldFirstName = oldFirstName;
                    auditLog.OldLastName = oldLastName;
                    auditLog.OldContactNumber = oldContactNumber;
                    auditLog.OldAddress = oldAddress;

                    // Mark the entity as modified and save changes
                    db.Entry(existingUser).State = EntityState.Modified;
                    db.SaveChanges();
                }

                return RedirectToAction("ManageAccount");
            }
            return View(aspNetUsers);
        }

        // GET: AspNetUsers/Delete/5
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpPost]
        public ActionResult DisableUser(string userEmail)
        {
            // Find the user by their email address
            var user = db.AspNetUsers.FirstOrDefault(u => u.Email == userEmail);

            if (user != null)
            {
                // Update the AccountStatus property to "Disable"
                user.AccountStatus = "Disable";

                // Save changes to the database
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
            }

            // You can redirect the user back to the page they came from
            // or any other appropriate action, such as returning to the user list.
            return RedirectToAction("Index"); // Replace "Index" with your actual action name
        }
        [HttpPost]
        public ActionResult UnDisableUser(string userEmail)
        {
            // Find the user by their email address
            var user = db.AspNetUsers.FirstOrDefault(u => u.Email == userEmail);

            if (user != null)
            {
                // Update the AccountStatus property to "Disable"
                user.AccountStatus = "UnDisable";

                // Save changes to the database
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
            }

            // You can redirect the user back to the page they came from
            // or any other appropriate action, such as returning to the user list.
            return RedirectToAction("DisableAccounts"); // Replace "Index" with your actual action name
        }



    }

}

Views/AspNetUsers/DisableAccounts.cshtml
@model IEnumerable<_1FinalCapstone.Models.AspNetUsers>

@{
    ViewBag.Title = "DisableAccounts";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .btn {
        display: inline-block;
        padding: 6px 12px;
        margin-bottom: 0;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        cursor: pointer;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        color: #333;
        background-color: #fff;
    }

    .btn-primary {
        color: #fff;
        background-color: #337ab7;
        border-color: #2e6da4;
    }

    .btn-danger {
        color: #fff;
        background-color: #d9534f;
        border-color: #d43f3a;
    }

    .btn-success {
        color: #fff;
        background-color: #5cb85c;
        border-color: #4cae4c;
    }
</style>
<br />


<h2><b>Disabled Accounts</b></h2>
<br />
<!-- Search input field -->
<div class="mb-2 d-flex justify-content-between">
    <input type="text" id="searchInput" class="form-control" placeholder="Search by User Name" />
    @Html.ActionLink("Go back to Accounts Listing", "Index", null, new { @class = "btn btn-primary btn-margin" })
</div>


<table>
    <tr>
        <th>
            Email
        </th>
        <th>
            Email Confirmed
        </th>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Address
        </th>
        <th>
            Contact Number
        </th>
        @*<th></th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailConfirmed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                <form method="post" action="@Url.Action("UnDisableUser", "AspNetUsers")">
                    @Html.Hidden("userEmail", item.Email)  @* Use userEmail instead of userId *@

                    <button type="submit" class="btn btn-danger">Enable</button>
                </form>
            </td>
        </tr>
    }
</table>

@section scripts {
    <script>
        // Function to filter the table rows based on the search input
        $(document).ready(function () {
            $("#searchInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("table tbody tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
                });
            });

            // Handle the "Disable" button click
            $(".btn-danger").click(function (e) {
                e.preventDefault(); // Prevent the default form submission

                var confirmation = confirm("Are you sure you want to Undisable the account?");
                if (confirmation) {
                    var userEmail = $(this).closest("form").find("input[name='userEmail']").val(); // Get the user's email
                    var form = $(this).closest("form"); // Find the parent form
                    form.find("input[name='userEmail']").val(userEmail); // Set the user's email
                    form.submit(); // Submit the form
                }
            });
        });
    </script>
}

Views/AspNetUsers/Edit.cshtml
@model _1FinalCapstone.Models.AspNetUsers

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<br />
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AspNetUsers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/AspNetUsers/EditAccount.cshtml
@model _1FinalCapstone.Models.AspNetUsers

@{
    ViewBag.Title = "EditAccount";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}


<style>


    body {
        background: #f5f5f5;
        margin-top: 20px;
    }

    .ui-w-80 {
        width: 80px !important;
        height: auto;
    }

    .btn-default {
        border-color: rgba(24, 28, 33, 0.1);
        background: rgba(0, 0, 0, 0);
        color: #4E5155;
    }

    label.btn {
        margin-bottom: 0;
    }

    .btn-outline-primary {
        border-color: #26B4FF;
        background: transparent;
        color: #26B4FF;
    }

    .btn {
        cursor: pointer;
    }

    .text-light {
        color: #babbbc !important;
    }

    .btn-facebook {
        border-color: rgba(0, 0, 0, 0);
        background: #3B5998;
        color: #fff;
    }

    .btn-instagram {
        border-color: rgba(0, 0, 0, 0);
        background: #000;
        color: #fff;
    }

    .card {
        background-clip: padding-box;
        box-shadow: 0 1px 4px rgba(24, 28, 33, 0.012);
    }

    .row-bordered {
        overflow: hidden;
    }

    .account-settings-fileinput {
        position: absolute;
        visibility: hidden;
        width: 1px;
        height: 1px;
        opacity: 0;
    }

    .account-settings-links .list-group-item.active {
        font-weight: bold !important;
    }

    html:not(.dark-style) .account-settings-links .list-group-item.active {
        background: transparent !important;
    }

    .account-settings-multiselect ~ .select2-container {
        width: 100% !important;
    }

    .light-style .account-settings-links .list-group-item {
        padding: 0.85rem 1.5rem;
        border-color: rgba(24, 28, 33, 0.03) !important;
    }

        .light-style .account-settings-links .list-group-item.active {
            color: #4e5155 !important;
        }

    .material-style .account-settings-links .list-group-item {
        padding: 0.85rem 1.5rem;
        border-color: rgba(24, 28, 33, 0.03) !important;
    }

        .material-style .account-settings-links .list-group-item.active {
            color: #4e5155 !important;
        }

    .dark-style .account-settings-links .list-group-item {
        padding: 0.85rem 1.5rem;
        border-color: rgba(255, 255, 255, 0.03) !important;
    }

        .dark-style .account-settings-links .list-group-item.active {
            color: #fff !important;
        }

    .light-style .account-settings-links .list-group-item.active {
        color: #4E5155 !important;
    }

    .light-style .account-settings-links .list-group-item {
        padding: 0.85rem 1.5rem;
        border-color: rgba(24, 28, 33, 0.03) !important;
    }
</style>



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Account</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container light-style flex-grow-1 container-p-y">
        <h4 class="font-weight-bold py-3 mb-4">
        </h4>
        <div class="card overflow-hidden">
            <div class="row no-gutters row-bordered row-border-light">
                <div class="col-md-3 pt-0">
                    <div class="list-group list-group-flush account-settings-links">
                        <a class="list-group-item list-group-item-action active">Account Settings</a>

                        <a class="list-group-item list-group-item-action active"
                           href="/AspNetUsers/ManageAccount">General</a>
                        <a class="list-group-item list-group-item-action"
                           href="~/Manage/ChangePassword">Change password</a>
                         
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="account-general">
                            <div class="card-body media align-items-center">
                                <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt
                                     class="d-block ui-w-80">

                            </div>
                            <hr class="border-light m-0">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Id)

                                    <div class="form-group">
                                        @Html.HiddenFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>

                                    <div class="form-group">
                                        @Html.HiddenFor(model => model.EmailConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>


                                    <div class="form-group">
                                        @Html.HiddenFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>

                                    <div class="form-group">
                                        @Html.HiddenFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>

                                    <div class="form-group">
                                        @Html.HiddenFor(model => model.LockoutEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>

                                    <div class="card-body">

                                        <div class="form-group">
                                            <label class="form-label">First Name</label>
                                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group">
                                            <label class="form-label">Last Name</label>
                                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group">
                                            @Html.HiddenFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                        </div>

                                        <div class="form-group">
                                            <label class="form-label">Address</label>
                                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group">
                                            <label class="form-label">Contact Number</label>
                                            @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Save" class="btn btn-primary" />
                                            </div>
                                        </div>

                                        <div>
                                            @Html.ActionLink("Back to List", "ManageAccount", null, new { @class = "btn btn-primary" })
                                        </div>

                                    </div>
                                </div>
                            }
                            </div>
                </div>
            </div>
        </div>
    </div>
    <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">

    </script>
</body>

</html>

Views/AspNetUsers/Index.cshtml
@model IEnumerable<_1FinalCapstone.Models.AspNetUsers>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .btn {
        display: inline-block;
        padding: 6px 12px;
        margin-bottom: 0;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        cursor: pointer;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        color: #333;
        background-color: #fff;
    }

    .btn-primary {
        color: #fff;
        background-color: #337ab7;
        border-color: #2e6da4;
    }

    .btn-danger {
        color: #fff;
        background-color: #d9534f;
        border-color: #d43f3a;
    }

    .btn-success {
        color: #fff;
        background-color: #5cb85c;
        border-color: #4cae4c;
    }
</style>
<br />


<h2><b>Accounts Management</b></h2>
<br />
<!-- Search input field -->
<div class="mb-2 d-flex justify-content-between">
    <input type="text" id="searchInput" class="form-control" placeholder="Search by User Name" />
    @Html.ActionLink("Go to Disable Accounts", "DisableAccounts", null, new { @class = "btn btn-primary btn-margin" })

</div>

<table>
    <tr>
        <th>
            Email
        </th>
        <th style="white-space: nowrap;">
            Email Confirmed
        </th>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Address
        </th>
        <th style="white-space: nowrap;">
            Contact Number
        </th>
        @*<th></th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailConfirmed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNumber)
            </td>
            <td>
                <form method="post" action="@Url.Action("DisableUser", "AspNetUsers")">
                    @Html.Hidden("userEmail", item.Email)  @* Use userEmail instead of userId *@

                    <button type="submit" class="btn btn-danger">Disable</button>
                </form>
            </td>
        </tr>
    }
</table>

@section scripts {
    <script>
        // Function to filter the table rows based on the search input
        $(document).ready(function () {
            $("#searchInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("table tbody tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
                });
            });

            // Handle the "Disable" button click
            $(".btn-danger").click(function (e) {
                e.preventDefault(); // Prevent the default form submission

                var confirmation = confirm("Are you sure you want to disable the account?");
                if (confirmation) {
                    var userEmail = $(this).closest("form").find("input[name='userEmail']").val(); // Get the user's email
                    var form = $(this).closest("form"); // Find the parent form
                    form.find("input[name='userEmail']").val(userEmail); // Set the user's email
                    form.submit(); // Submit the form
                }
            });
        });
    </script>
}